### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by JaneChik** [shmohammadi86/ACTIONet#24]
Hello,

I was trying to install ACTIONet (R version) on Ubuntu 20.04, but faced a few problems. 
Before installing I followed all steps discussed in the tutorial except installing _Intel Math Kernel Library (MKL)_.

Here are my attempts to install ACTIONet in several ways:

1. **R-release** version _(from Rstudio)_:
`devtools::install_github("shmohammadi86/ACTIONet", ref = "R-release")`
This command resulted in the **total freezing** of the laptop at some point of the installation. I had to force a computer shutdown. 

2. **R-devel** version _(from Rstudio)_:
`devtools::install_github("shmohammadi86/ACTIONet", ref = "R-devel")`
The same as for R-release. 

3. **R-release** version _(from terminal)_:
Installing directly from the clone resulted in the **similar issue** (computer freezing). 

4. **R-devel** version _(from terminal)_:
Installing from **terminal** showed that _ACTIONetExperiment_ package is needed. After installing this package there were a few messages that some files are missing and therefore the installation is impossible. 

> find: ‘/home/evgenia/SpringProjectGAM/ProjectGAM/year_2/ACTIONet/src/ACTIONet/include’: No such file or directory
> find: ‘/home/evgenia/SpringProjectGAM/ProjectGAM/year_2/ACTIONet/src/ACTIONet/include’: No such file or directory
> find: ‘/home/evgenia/SpringProjectGAM/ProjectGAM/year_2/ACTIONet/src/ACTIONet/include’: No such file or directory
> find: ‘/home/evgenia/SpringProjectGAM/ProjectGAM/year_2/ACTIONet/src/ACTIONet/include’: No such file or directory
> In file included from RcppExports.cpp:4:
> ../inst/include/ACTIONet.h:5:10: fatal error: base.h: No such file or directory
>     5 | #include <base.h>
>       |          ^~~~~~~~
> In file included from RCpp_util.cpp:1:
> ../inst/include/ACTIONet.h:5:10: fatal error: base.h: No such file or directory
>     5 | #include <base.h>
>       |          ^~~~~~~~
> In file included from ACTIONet.cpp:1:
> ../inst/include/ACTIONet.h:5:10: fatal error: base.h: No such file or directory
>     5 | #include <base.h>
>       |          ^~~~~~~~
> compilation terminated.
> compilation terminated.
> compilation terminated.
> make: *** [/usr/lib/R/etc/Makeconf:177: RCpp_util.o] Error 1
> make: *** Waiting for unfinished jobs....
> make: *** [/usr/lib/R/etc/Makeconf:177: ACTIONet.o] Error 1
> make: *** [/usr/lib/R/etc/Makeconf:177: RcppExports.o] Error 1
> ERROR: compilation failed for package ‘ACTIONet’
> * removing ‘/home/evgenia/R/x86_64-pc-linux-gnu-library/4.1/ACTIONet’

It would be great if you could help with the installation!
Thank you!

**Comment by sebastianpineda** [comment]
Hi Evgenia. The current 'devel' is unstable since we're moving some of the underlying dependencies that were previously part of this package into a separate stand-alone package.

Nevertheless, your compiler is exhibiting some strange behavior. It's searching for headers in "ACTIONet/src/ACTIONet/include". R packages store headers in "inst/include", so the search path should be "ACTIONet/inst/include", which is present and includes the supposedly missing files. This is standard for all Rcpp packages, so I'm not sure why this is happening on your system. Are you using a non-standard compiler by any chance? Have you had any trouble compiling other packages/software?

Unfortunately I am not able to reproduce your problem. I tried reinstalling release from source both on a local machine and a clean VM, and it installed just fine on Ubuntu 20 and macOS. Do you have all the required linux packages (`libhdf5-dev libsuitesparse-dev libcurl4-openssl-dev libssl-dev libxml2-dev`)? If so, my first recommendation would be to reinstall your build tools and try again.

As for your docker issue, we are trying to debug this. My guess is that the issues might be related.

**Comment by JaneChik** [comment]
Hello Sebastian!
Indeed my computer behaved very strangely and I couldn't figure out why. 
Here I attache list of compilers used by my machine at the time I encountered this problem with installation 
![compiler](https://user-images.githubusercontent.com/47989785/220398986-9e782769-6328-4323-8a6c-b4022f4cda26.jpg)

Maybe somehow it will be helpful

**Comment by JaneChik** [comment]
Currently both versions "R-release" and "R-devel" can be installed successfully. Although at my first attempt there was freezing like previously but next time it was somehow resolved. 
Unfortunately, I am not sure what was the cause of trouble previously (some time ago I reinstalled Ubuntu)
